spring.application.name=UniBazaarBackend
server.servlet.context-path=/api/v1

#Spring Security Config
server.servlet.session-cookie-same-site=lax
server.servlet.session.timeout=1m

#Actuators
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

#DB Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=dev

