server.port=${PORT}

#Postgre Config
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.url=${DB_URL}

#Redis Config
spring.data.redis.url=${REDIS_URL}

#HMAC_KEY
hmac.secret=${HMAC_SECRET}

#OAuth Config
spring.security.oauth2.client.registration.google.client-id=${OAuth_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAuth_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${OAuth_URL}

#Cloudinary Config
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}

#Perspective Config
perspective.api.key=${PERSPECTIVE_API_KEY}
